### ISSUE TITLE
How to compile on Linux

### ISSUE THREAD

**Issue by air3ijai** [german77/TheDudeToHuman#1]
Hello,

I'm checking how get a binary on Linux, but got an error on Ubuntu 24.04
```shell
# Requirements
apt update && apt install cmake g++ libssh2-1-dev

# Sources
git clone https://github.com/german77/TheDudeToHuman.git
cd TheDudeToHuman
git submodule update --init --recursive

# Build
cmake -S . -B build
cmake --build build --target the_dude_to_human
```

**Error**
```shell
root@dude:/opt/TheDudeToHuman/TheDudeToHuman# cmake --build build --target the_dude_to_human
[ 30%] Built target zlib
[ 34%] Built target sqlite
[ 84%] Built target libssh2_shared
[ 84%] Building CXX object src/the_dude_to_human/CMakeFiles/the_dude_to_human.dir/gzip/gzip.cpp.o
/opt/TheDudeToHuman/TheDudeToHuman/src/the_dude_to_human/gzip/gzip.cpp:12:6: error: no previous declaration for ‘bool DecompressFiles(gzFile, FILE*)’ [-Werror=missing-declarations]
   12 | bool DecompressFiles(gzFile in, FILE* out) {
      |      ^~~~~~~~~~~~~~~
/opt/TheDudeToHuman/TheDudeToHuman/src/the_dude_to_human/gzip/gzip.cpp: In member function ‘bool Gzip::Gzip::IsGzipFile()’:
/opt/TheDudeToHuman/TheDudeToHuman/src/the_dude_to_human/gzip/gzip.cpp:45:57: error: narrowing conversion of ‘139’ from ‘unsigned int’ to ‘char’ [-Wnarrowing]
   45 |     constexpr std::array<char, 2> gzip_signature{0x1Fu, 0x8Bu};
      |                                                         ^~~~~
/opt/TheDudeToHuman/TheDudeToHuman/src/the_dude_to_human/gzip/gzip.cpp: In member function ‘bool Gzip::Gzip::Decompress(const std::string&)’:
/opt/TheDudeToHuman/TheDudeToHuman/src/the_dude_to_human/gzip/gzip.cpp:64:9: error: ‘fopen_s’ was not declared in this scope; did you mean ‘fopen64’?
   64 |     if (fopen_s(&out, out_file.c_str(), "wb") != 0) {
      |         ^~~~~~~
      |         fopen64
cc1plus: some warnings being treated as errors
gmake[3]: *** [src/the_dude_to_human/CMakeFiles/the_dude_to_human.dir/build.make:118: src/the_dude_to_human/CMakeFiles/the_dude_to_human.dir/gzip/gzip.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:2152: src/the_dude_to_human/CMakeFiles/the_dude_to_human.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:2159: src/the_dude_to_human/CMakeFiles/the_dude_to_human.dir/rule] Error 2
gmake: *** [Makefile:1034: the_dude_to_human] Error 2
```

<img width="1269" alt="Image" src="https://github.com/user-attachments/assets/a520c120-d592-4611-b232-a6e5c9103449" />

**Comment by air3ijai** [comment]
Now, build is working - thanks
```shell
./build/bin/the_dude_to_human --help

Usage: ./build/bin/the_dude_to_human [options] <filename>
--f, --file                                 Load the specified database file
--o, --out                                  Store database location
--m, --mikrotik=user:password@address:port  Connect to the specified mikrotik device
--h, --help                                 Display this help and exit
```
Btw, shouldn't a short option be with a single dash?
<details><summary>example</summary>

```shell
curl -h
Usage: curl [options...] <url>
 -d, --data <data>          HTTP POST data
 -f, --fail                 Fail fast with no output on HTTP errors
 -h, --help <category>      Get help for commands
 -i, --include              Include protocol response headers in the output
 -o, --output <file>        Write to file instead of stdout
 -O, --remote-name          Write output to a file named as the remote file
 -s, --silent               Silent mode
 -T, --upload-file <file>   Transfer local FILE to destination
 -u, --user <user:password> Server user and password
 -A, --user-agent <name>    Send User-Agent <name> to server
 -v, --verbose              Make the operation more talkative
 -V, --version              Show version number and quit

This is not the full help, this menu is stripped into categories.
Use "--help category" to get an overview of all categories.
For all options use the manual or "--help all".
```
</details>

```diff
+ -f, --file                                 Load the specified database file
- --f, --file                                Load the specified database file
```

Checking functionality
```shell
./build/bin/the_dude_to_human --file /opt/dude.db --out /opt/out.csv

Reading database /opt/dude.db
Opened database successfully
Map 10159: Local
Device 20204: CHR
Saving database /opt/out.csv
```

Checking the result
```shell
ls -la /opt/out.csv
ls: cannot access '/opt/out.csv': No such file or directory
```

Probably it make sense to create a separate issue about functionality.

**Comment by german77** [comment]
I agree it should be one dash but for some reason is not working that way. I need to dig deeper into that issue.

As I mentioned earlier  `there's no way to save it` the save function is stubbed and doesn't do anything yet. I still need to implement that part. I was adding support to sql but that led to some rework on the data parser and left the project for a bit.

Let me see if I can get something simpler like a csv or json that doesn't involve dealing with sockets or queries. To just dump the whole object as is.

**Comment by german77** [comment]
Update. I just added some basic support for json. Now if you use `--out` it will actually write the database to a file in json format. Most tables are missing but I will add them later when I have time.

**Comment by air3ijai** [comment]
Checked `./build/bin/the_dude_to_human --file /opt/dude.db --out /opt/out.json` and it works.

Let's close the issue as we have a way to compile binary on Linux and get basic data in json.

Thank you!

**Comment by air3ijai** [comment]
Thank you for the update!

Btw, what do you think about adding a precompiled binaries?

GitHub provides [Linux/macOS/Windows x86/arm runners](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories). I can participate and create a PR, but would need your assistance with compilation steps.

We could use [softprops/action-gh-release](https://github.com/softprops/action-gh-release) or [other options](https://github.com/actions/create-release#github-action---releases-api) as well, or maybe you have other experience or preferences.

**Comment by german77** [comment]
I do plan to add releases. But the tool isn't quite complete yet. I want it to be fully functional before making any binaries for public. Since exporting the database is already done, only thing left is connect to the dude via ssh and download the database. I'm fine with adding the actions setup right now. Specially setting up CI so I don't accidentally break compilation like it happened on linux.

I already added code to connect via ssh and is able to execute commands. I just need to figure out how to download the file itself along with some user feedback as my database is +2GB in size and I don't want to make it feel like the program is stuck while that happens. Decompressing the database also takes a heck of a long time.

**Comment by air3ijai** [comment]
Did a simple check and got the following results - probably something needs to be adjusted for macOS/Windows

<details><summary><code>test.yaml</code></summary>


**`.github/workflows/test.yaml`**

```yaml
name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            cpu: amd64
            builder: ubuntu-latest
            shell: bash --noprofile --norc -e -o pipefail

          - os: linux
            cpu: arm64
            builder: ubuntu-24.04-arm
            shell: bash --noprofile --norc -e -o pipefail

          - os: macos
            cpu: amd64
            builder: macos-13
            shell: bash --noprofile --norc -e -o pipefail

          - os: macos
            cpu: arm64
            builder: macos-latest
            shell: bash --noprofile --norc -e -o pipefail

          - os: windows
            cpu: amd64
            builder: windows-latest
            shell: pwsh

          - os: windows
            cpu: arm64
            builder: windows-11-arm
            shell: pwsh

    defaults:
      run:
        shell: ${{ matrix.shell }} {0}

    name: ${{ matrix.os }}-${{ matrix.cpu }}
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --target the_dude_to_human
```
</details>

<img width="310" alt="Image" src="https://github.com/user-attachments/assets/cc790898-a3e8-4f7f-ac31-7470356aca45" />
